# Generated by Django 2.2.18 on 2023-12-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=45)),
                ('fecha', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'access_control',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Arc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'arc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Authassignment',
            fields=[
                ('itemname', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=64)),
                ('bizrule', models.TextField(blank=True, null=True)),
                ('data', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'authassignment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Authitem',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('bizrule', models.TextField(blank=True, null=True)),
                ('data', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'authitem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Authitemchild',
            fields=[
                ('parent', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('child', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'authitemchild',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=250)),
                ('parent', models.IntegerField(blank=True, null=True)),
                ('url', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'categoria_documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250)),
                ('autor', models.CharField(max_length=250)),
                ('anno_pub', models.IntegerField()),
                ('gestor_doc', models.CharField(max_length=100)),
                ('fecha_sub', models.CharField(max_length=50)),
                ('id_categoria', models.IntegerField()),
            ],
            options={
                'db_table': 'documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=250)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('tipo', models.CharField(blank=True, max_length=600, null=True)),
            ],
            options={
                'db_table': 'grupo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InfCump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_trab', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('anno', models.IntegerField()),
                ('inf_cualitativo', models.CharField(blank=True, max_length=1000, null=True)),
                ('valoracion', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'inf_cump',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=500)),
                ('autor', models.IntegerField()),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'noticia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObjAnual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'obj_anual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObjEspecifico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'obj_especifico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObjEstrategico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'obj_estrategico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Otra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'otra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.CharField(max_length=250)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('url', models.CharField(max_length=100)),
                ('icono', models.CharField(blank=True, max_length=150, null=True)),
                ('menu', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('padre', models.CharField(max_length=50)),
                ('visible', models.IntegerField()),
            ],
            options={
                'db_table': 'permiso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=250)),
                ('siglas', models.CharField(max_length=10)),
                ('cliente', models.CharField(max_length=150)),
                ('alcance', models.CharField(max_length=25)),
                ('responsable_des', models.CharField(max_length=100)),
                ('responsable_ar', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProyectoParticipante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_participante', models.IntegerField()),
            ],
            options={
                'db_table': 'proyecto_participante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=45)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'rol_permiso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=150)),
                ('descripcion_rol', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'rol_proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=50)),
                ('sede', models.CharField(blank=True, max_length=100, null=True)),
                ('horario', models.CharField(blank=True, max_length=50, null=True)),
                ('otro_horario', models.CharField(blank=True, max_length=50, null=True)),
                ('contable', models.CharField(blank=True, max_length=2, null=True)),
                ('extra', models.CharField(max_length=2)),
                ('motivo', models.CharField(blank=True, max_length=500, null=True)),
                ('creada_por', models.CharField(max_length=8)),
                ('gestor', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'tarea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TareaColectiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tarea', models.IntegerField()),
                ('id_tarea_asociada', models.IntegerField(blank=True, null=True)),
                ('cumplimiento', models.IntegerField()),
                ('comentario', models.CharField(blank=True, max_length=500, null=True)),
                ('otros', models.CharField(blank=True, max_length=255, null=True)),
                ('mostrar', models.CharField(blank=True, max_length=255, null=True)),
                ('modificada', models.IntegerField(blank=True, null=True)),
                ('id_area', models.IntegerField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tarea_colectiva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TareaDireccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tarea', models.IntegerField()),
                ('cumplimiento', models.IntegerField()),
                ('comentario', models.CharField(blank=True, max_length=500, null=True)),
                ('otros', models.CharField(blank=True, max_length=255, null=True)),
                ('mostrar', models.CharField(blank=True, max_length=255, null=True)),
                ('modificada', models.IntegerField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tarea_direccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TareaInd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('asunto', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('responsable', models.CharField(max_length=255)),
                ('observaciones', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tarea_ind',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TareaIndividual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cumplimiento', models.CharField(max_length=12)),
                ('comentario', models.CharField(blank=True, max_length=2500, null=True)),
                ('modificada', models.IntegerField(blank=True, null=True)),
                ('id_trab', models.CharField(max_length=8)),
                ('responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('hora_inicio', models.CharField(blank=True, max_length=10, null=True)),
                ('hora_fin', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha', models.DateField()),
                ('sede', models.CharField(max_length=100)),
                ('justificacion', models.CharField(blank=True, max_length=2500, null=True)),
            ],
            options={
                'db_table': 'tarea_individual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TareaPgIndividual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_trab', models.IntegerField()),
            ],
            options={
                'db_table': 'tarea_pg_individual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TareaPrincipal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'tarea_principal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TareaPrincipalTrabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('anno', models.IntegerField()),
            ],
            options={
                'db_table': 'tarea_principal_trabajador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tarea', models.IntegerField()),
                ('cumplimiento', models.CharField(max_length=12)),
                ('comentario', models.CharField(blank=True, max_length=500, null=True)),
                ('modificada', models.IntegerField(blank=True, null=True)),
                ('id_trab', models.CharField(max_length=8)),
                ('responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('hora_inicio', models.CharField(blank=True, max_length=10, null=True)),
                ('hora_fin', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha', models.DateField()),
                ('sede', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestNoslen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'test_noslen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrabGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'trab_grupo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrabProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_area', models.IntegerField()),
            ],
            options={
                'db_table': 'trab_proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trazas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('usuario', models.CharField(max_length=45)),
                ('evento', models.CharField(max_length=45)),
                ('resumen', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'trazas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=75)),
                ('sap_code', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
