# Generated by Django 4.0 on 2023-12-26 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarea',
            options={'managed': False, 'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
        migrations.AlterModelOptions(
            name='tareaindividual',
            options={'managed': False, 'verbose_name': 'Tarea individual', 'verbose_name_plural': 'Tareas individuales'},
        ),
        migrations.AlterModelOptions(
            name='tareaprincipal',
            options={'managed': False, 'verbose_name': 'Tarea principal', 'verbose_name_plural': 'Tareas principales'},
        ),
    ]
