# Generated by Django 4.0 on 2023-12-26 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_alter_tarea_options_alter_tareaindividual_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupo',
            options={'managed': False, 'verbose_name': 'Grupo', 'verbose_name_plural': 'Grupos'},
        ),
    ]
