# Generated by Django 4.2.3 on 2024-01-17 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_alter_grupo_options'),
    ]

    operations = [
    ]
