# Generated by Django 4.2.3 on 2024-02-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_auto_20240117_0421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('segmento', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaIndicadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cat', models.CharField(max_length=100)),
                ('descripcion_cat', models.CharField(max_length=100)),
                ('estado_cat', models.IntegerField()),
            ],
            options={
                'db_table': 'categoria_indicadores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('anno', models.IntegerField()),
                ('lugar', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_inicio', models.CharField(blank=True, max_length=12, null=True)),
                ('fecha_fin', models.CharField(blank=True, max_length=12, null=True)),
                ('modalidad', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Galleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=2500)),
                ('codigo', models.IntegerField()),
                ('monto', models.FloatField()),
            ],
            options={
                'db_table': 'galleta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndicadorValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=50)),
                ('plan', models.CharField(blank=True, max_length=50, null=True)),
                ('mes', models.IntegerField()),
                ('anno', models.IntegerField()),
                ('fecha_carga', models.DateField()),
                ('nivel', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'indicador_valor',
                'ordering': ['-fecha_carga'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=250)),
                ('comportamiento', models.CharField(max_length=50)),
                ('formato', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('formula', models.CharField(blank=True, max_length=100, null=True)),
                ('icono', models.CharField(max_length=100)),
                ('sec_cards', models.IntegerField()),
            ],
            options={
                'db_table': 'meta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=2500)),
                ('descripcion', models.CharField(max_length=2500)),
            ],
            options={
                'db_table': 'mision',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_municipio', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'municipio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_descripcion', models.CharField(max_length=1500)),
                ('notif_fecha', models.CharField(max_length=20)),
                ('notif_estado', models.IntegerField()),
                ('notif_url', models.CharField(max_length=250)),
                ('notif_tipo', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'notificacion',
                'ordering': ['-notif_fecha'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotificacionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vis', models.CharField(max_length=20)),
                ('estado_vis', models.IntegerField()),
                ('visto', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notificacion_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=2500)),
                ('descripcion', models.CharField(max_length=2500)),
                ('anno', models.IntegerField()),
            ],
            options={
                'db_table': 'objetivo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaginaExcluida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pagina', models.CharField(max_length=250)),
                ('descripcion_pagina', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'pagina_excluida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('siglas', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'provincia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('um_nombre', models.CharField(max_length=50)),
                ('um_descripcion', models.CharField(max_length=250)),
                ('um_estado', models.IntegerField()),
            ],
            options={
                'db_table': 'unidad_medida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Valor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1500)),
                ('descripcion', models.CharField(max_length=5000)),
            ],
            options={
                'db_table': 'valor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=2500)),
                ('descripcion', models.CharField(max_length=2500)),
            ],
            options={
                'db_table': 'vision',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Arc',
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
        migrations.DeleteModel(
            name='InfCump',
        ),
        migrations.DeleteModel(
            name='ObjAnual',
        ),
        migrations.DeleteModel(
            name='ObjEspecifico',
        ),
        migrations.DeleteModel(
            name='ObjEstrategico',
        ),
        migrations.DeleteModel(
            name='Otra',
        ),
        migrations.DeleteModel(
            name='Proyecto',
        ),
        migrations.DeleteModel(
            name='ProyectoParticipante',
        ),
        migrations.DeleteModel(
            name='RolProyecto',
        ),
        migrations.DeleteModel(
            name='Tarea',
        ),
        migrations.DeleteModel(
            name='TareaColectiva',
        ),
        migrations.DeleteModel(
            name='TareaDireccion',
        ),
        migrations.DeleteModel(
            name='TareaInd',
        ),
        migrations.DeleteModel(
            name='TareaIndividual',
        ),
        migrations.DeleteModel(
            name='TareaPgIndividual',
        ),
        migrations.DeleteModel(
            name='TareaPrincipal',
        ),
        migrations.DeleteModel(
            name='TareaPrincipalTrabajador',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TestNoslen',
        ),
        migrations.DeleteModel(
            name='TrabGrupo',
        ),
        migrations.DeleteModel(
            name='TrabProyecto',
        ),
        migrations.AlterModelOptions(
            name='documento',
            options={'managed': False, 'ordering': ['-fecha_sub', '-hora_sub']},
        ),
        migrations.AlterModelOptions(
            name='noticia',
            options={'managed': False, 'ordering': ['-fecha_creacion', '-hora_creacion']},
        ),
        migrations.AlterModelOptions(
            name='trazas',
            options={'managed': False, 'ordering': ['-fecha', '-hora']},
        ),
    ]
